wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.13
    start_time: 1683955485.633858
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      - 76
      2:
      - 1
      - 5
      - 53
      - 55
      - 76
      3:
      - 13
      - 23
      4: 3.8.13
      5: 0.13.4
      8:
      - 5
batch_size:
  desc: null
  value: 2048
beta_class:
  desc: null
  value: 0.9
category_balance:
  desc: null
  value: true
context_code_dim:
  desc: null
  value: 16
dataset:
  desc: null
  value: TaoBao
embed_size:
  desc: null
  value: 16
epoch:
  desc: null
  value: 1000
gamma:
  desc: null
  value: 2.0
gpu:
  desc: null
  value: 0
hidden_size:
  desc: null
  value: 32
k:
  desc: null
  value: 20
k_experts:
  desc: null
  value: 2
k_list:
  desc: null
  value:
  - 100
  - 300
layers:
  desc: null
  value: 1
lr:
  desc: null
  value: 0.05
metrics:
  desc: null
  value:
  - recall
  - hit_ratio
  - coverage
model:
  desc: null
  value: moe
moe:
  desc: null
  value: true
n_experts:
  desc: null
  value: 5
neg_number:
  desc: null
  value: 4
num_context_codes:
  desc: null
  value: 16
patience:
  desc: null
  value: 10
seed:
  desc: null
  value: 2022
sigma:
  desc: null
  value: 1.0
wandb_enable:
  desc: null
  value: true
weight_decay:
  desc: null
  value: 8.0e-08
